import type { Metadata } from "next";
import { Inter, Montserrat, Mulish } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/effects/SmoothScroll";
import Sidebar from "./components/common/Sidebar";
import Header from "./components/common/Header";
import Footer from "./components/common/Footer";

const inter = Mulish({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Rahul's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScroll>
          <Sidebar />
          <Header />
          {children}
          <Footer />
        </SmoothScroll>
      </body>
    </html>
  );
}
