import type { Metadata } from "next";
import { Inter, Montserrat,Mulish } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/effects/SmoothScroll";

const inter = Mulish({ subsets: ["latin"], weight: ['400'] });

export const metadata: Metadata = {
  title: "Rahul's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SmoothScroll>
          {children}
        </SmoothScroll>
      </body>
    </html>
  );
}
